name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
        #   - x86_64-pc-windows-msvc
        #   - x86_64-apple-darwin
        # include:
        #   - target: x86_64-unknown-linux-musl
        #     os: ubuntu-latest
        #   - target: x86_64-pc-windows-msvc
        #     os: windows-latest
        #   - target: x86_64-apple-darwin
        #     os: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install musl tools
      if : matrix.target == 'x86_64-unknown-linux-musl'
      run: |
        sudo apt install -qq -y musl-tools --no-install-recommends
    
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{matrix.target}}
        override: true

    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl
    - name: Check
      run: ldd target/x86_64-unknown-linux-musl/release/mcmodsmgr
    - name: Run tests
      run: cargo test
