name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make build
    - name: Run tests
      run: cargo test --verbose
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Executable
        path: target/x86_64-unknown-linux-musl/release/mcmodsmgr


  build:
    runs-on: ${{matrix.os}}
    timeout-minutes: 5

    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: maxos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        target: ${{matrix.target}}

    - name: Build
      run: cargo build --release --target ${{matrix.target}}

    - name: Run tests
      run: cargo test

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Executable
        path: target/${{matrix.target}}/release/mcmodsmgr
