name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl
    - name: Check
      run: ldd target/x86_64-unknown-linux-musl/release/mcmodsmgr
    - name: Run tests
      run: cargo test
